### PR TITLE
Type hints and await-termination

### PR DESCRIPTION
**Pull request by piranha**
`await-termination` is something I've spent half an hour looking for, let's make it more visible. :)

### CODE REVIEW

**Comment by tolitius** [comment]
good point about `await-termination` and thank you for PR!

one thing that would make it "complete" is `shutdown` vs. `shutdown-now`
since the existing `shutdown`:

```clojure
(defn shutdown
  "Request termination, waiting for current tasks to finish"
  [^ThreadPoolExecutor pool]
  (.shutdownNow pool))
```

[won't wait](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/concurrent/ExecutorService.html#shutdownNow()) for the "current tasks to finish".

```clojure
(defn shutdown
  "Request termination, waiting for current tasks to finish"
  [^ThreadPoolExecutor pool]
  (.shutdown pool))
```

would :)

probably good to have them both to avoid a wrong expectation

**Comment by sansolovyov** [comment]
I'm not attentive enough 😁

**Comment by sansolovyov** [comment]
How do you like that approach to naming? Or is it better to stick to official naming? :)

**Comment by tolitius** [comment]
love it :)

first thought is: "both shutdowns are side effectful, so `!` is unclear"
second and final thought: "this makes soo much sence humanwise":
image

**Pull request merged**
